import type { BoardCellDef } from './types'

/**
 * 24 格順時針；0 為起點。
 * 同色地產在路徑上相鄰成對，方便辨識與「同色壟斷」。
 * 索引 9 固定為監獄（與 JAIL_POSITION 一致）。
 */
export const BOARD: BoardCellDef[] = [
  { kind: 'go', id: 'go', name: '起點' },
  {
    kind: 'property',
    id: 'p1',
    name: '基隆廟口',
    group: 'brown',
    price: 60,
    baseRent: 2,
  },
  {
    kind: 'property',
    id: 'p2',
    name: '九份老街',
    group: 'brown',
    price: 60,
    baseRent: 4,
  },
  { kind: 'chance', id: 'ch1', name: '機會' },
  {
    kind: 'property',
    id: 'p3',
    name: '羅東夜市',
    group: 'light_blue',
    price: 100,
    baseRent: 6,
  },
  {
    kind: 'property',
    id: 'p4',
    name: '花蓮太魯閣',
    group: 'light_blue',
    price: 100,
    baseRent: 6,
  },
  { kind: 'tax', id: 'tax1', name: '所得稅', amount: 200 },
  {
    kind: 'property',
    id: 'p5',
    name: '逢甲夜市',
    group: 'pink',
    price: 140,
    baseRent: 10,
  },
  {
    kind: 'property',
    id: 'p6',
    name: '彩虹眷村',
    group: 'pink',
    price: 140,
    baseRent: 10,
  },
  { kind: 'jail', id: 'jail', name: '監獄／探視' },
  {
    kind: 'property',
    id: 'p7',
    name: '愛河',
    group: 'orange',
    price: 180,
    baseRent: 14,
  },
  {
    kind: 'property',
    id: 'p8',
    name: '西子灣',
    group: 'orange',
    price: 180,
    baseRent: 14,
  },
  { kind: 'parking', id: 'park', name: '免費停車' },
  {
    kind: 'property',
    id: 'p9',
    name: '阿里山',
    group: 'red',
    price: 220,
    baseRent: 18,
  },
  {
    kind: 'property',
    id: 'p10',
    name: '日月潭',
    group: 'red',
    price: 220,
    baseRent: 18,
  },
  { kind: 'chance', id: 'ch2', name: '機會' },
  {
    kind: 'property',
    id: 'p11',
    name: '墾丁大街',
    group: 'yellow',
    price: 260,
    baseRent: 22,
  },
  {
    kind: 'property',
    id: 'p12',
    name: '台北101',
    group: 'yellow',
    price: 260,
    baseRent: 22,
  },
  { kind: 'chest', id: 'chest1', name: '命運' },
  {
    kind: 'railroad',
    id: 'r1',
    name: '北迴線',
    price: 200,
    rents: [25, 50],
  },
  { kind: 'chest', id: 'chest2', name: '命運' },
  {
    kind: 'railroad',
    id: 'r2',
    name: '高鐵站',
    price: 200,
    rents: [25, 50],
  },
  { kind: 'tax', id: 'tax2', name: '奢侈稅', amount: 100 },
  { kind: 'goto_jail', id: 'goto', name: '進監獄' },
]
