import type { BoardCellDef } from './types'

type WithoutColorGroup<T> = T extends any ? Omit<T, 'colorGroup'> : never
type RawBoardCellDef = WithoutColorGroup<BoardCellDef>

/**
 * 40 格順時針（經典大富翁規模）；0 為起點（左下）。
 * 路徑：底邊 0→10 → 右邊 11→19 → 頂邊 20→30 → 左邊 31→39。
 * 索引 10 為監獄／探視；索引 30 為入獄（送往 10）。
 */
const RAW_BOARD: RawBoardCellDef[] = [
  { kind: 'go', id: 'go', name: '起點' },
  {
    kind: 'property',
    id: 'p_b1',
    name: '基隆廟口',
    group: 'brown',
    price: 60,
    baseRent: 2,
  },
  { kind: 'chest', id: 'chest1', name: '命運' },
  {
    kind: 'property',
    id: 'p_b2',
    name: '九份老街',
    group: 'brown',
    price: 60,
    baseRent: 4,
  },
  { kind: 'tax', id: 'tax1', name: '所得稅', amount: 200 },
  {
    kind: 'railroad',
    id: 'r1',
    name: '北迴線',
    price: 200,
    rents: [25, 50, 100, 200],
  },
  {
    kind: 'property',
    id: 'p_lb1',
    name: '羅東夜市',
    group: 'light_blue',
    price: 100,
    baseRent: 6,
  },
  { kind: 'chance', id: 'ch1', name: '機會' },
  {
    kind: 'property',
    id: 'p_lb2',
    name: '花蓮太魯閣',
    group: 'light_blue',
    price: 100,
    baseRent: 6,
  },
  {
    kind: 'property',
    id: 'p_lb3',
    name: '台東熱氣球',
    group: 'light_blue',
    price: 120,
    baseRent: 8,
  },
  { kind: 'jail', id: 'jail', name: '監獄／探視' },
  {
    kind: 'property',
    id: 'p_pk1',
    name: '逢甲夜市',
    group: 'pink',
    price: 140,
    baseRent: 10,
  },
  {
    kind: 'utility',
    id: 'u1',
    name: '台電',
    price: 150,
  },
  {
    kind: 'property',
    id: 'p_pk2',
    name: '彩虹眷村',
    group: 'pink',
    price: 140,
    baseRent: 10,
  },
  {
    kind: 'property',
    id: 'p_pk3',
    name: '清境農場',
    group: 'pink',
    price: 160,
    baseRent: 12,
  },
  {
    kind: 'railroad',
    id: 'r2',
    name: '高鐵左營',
    price: 200,
    rents: [25, 50, 100, 200],
  },
  {
    kind: 'property',
    id: 'p_or1',
    name: '愛河',
    group: 'orange',
    price: 180,
    baseRent: 14,
  },
  { kind: 'chest', id: 'chest2', name: '命運' },
  {
    kind: 'property',
    id: 'p_or2',
    name: '西子灣',
    group: 'orange',
    price: 180,
    baseRent: 14,
  },
  {
    kind: 'property',
    id: 'p_or3',
    name: '旗津老街',
    group: 'orange',
    price: 200,
    baseRent: 16,
  },
  { kind: 'parking', id: 'park', name: '免費停車' },
  {
    kind: 'property',
    id: 'p_rd1',
    name: '阿里山',
    group: 'red',
    price: 220,
    baseRent: 18,
  },
  { kind: 'chance', id: 'ch2', name: '機會' },
  {
    kind: 'property',
    id: 'p_rd2',
    name: '日月潭',
    group: 'red',
    price: 220,
    baseRent: 18,
  },
  {
    kind: 'property',
    id: 'p_rd3',
    name: '合歡山',
    group: 'red',
    price: 240,
    baseRent: 20,
  },
  {
    kind: 'railroad',
    id: 'r3',
    name: '台鐵縱貫',
    price: 200,
    rents: [25, 50, 100, 200],
  },
  {
    kind: 'property',
    id: 'p_yl1',
    name: '墾丁大街',
    group: 'yellow',
    price: 260,
    baseRent: 22,
  },
  {
    kind: 'property',
    id: 'p_yl2',
    name: '台北101',
    group: 'yellow',
    price: 260,
    baseRent: 22,
  },
  {
    kind: 'utility',
    id: 'u2',
    name: '台水',
    price: 150,
  },
  {
    kind: 'property',
    id: 'p_yl3',
    name: '野柳女王頭',
    group: 'yellow',
    price: 280,
    baseRent: 24,
  },
  { kind: 'goto_jail', id: 'goto', name: '進監獄' },
  {
    kind: 'property',
    id: 'p_gr1',
    name: '太魯閣步道',
    group: 'green',
    price: 300,
    baseRent: 26,
  },
  {
    kind: 'property',
    id: 'p_gr2',
    name: '武陵農場',
    group: 'green',
    price: 300,
    baseRent: 26,
  },
  { kind: 'chest', id: 'chest3', name: '命運' },
  {
    kind: 'property',
    id: 'p_gr3',
    name: '平溪天燈',
    group: 'green',
    price: 320,
    baseRent: 28,
  },
  {
    kind: 'railroad',
    id: 'r4',
    name: '機場捷運',
    price: 200,
    rents: [25, 50, 100, 200],
  },
  { kind: 'chance', id: 'ch3', name: '機會' },
  {
    kind: 'property',
    id: 'p_db1',
    name: '信義商圈',
    group: 'dark_blue',
    price: 350,
    baseRent: 35,
  },
  { kind: 'tax', id: 'tax2', name: '奢侈稅', amount: 100 },
  {
    kind: 'property',
    id: 'p_db2',
    name: '西門町',
    group: 'dark_blue',
    price: 400,
    baseRent: 50,
  },
]

function withColorGroup(cell: RawBoardCellDef): BoardCellDef {
  if (cell.kind === 'property') return { ...cell, colorGroup: cell.group }
  return { ...cell, colorGroup: cell.kind }
}

export const BOARD: BoardCellDef[] = RAW_BOARD.map(withColorGroup)
